/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as NowRouteImport } from './routes/now'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as StudioWritingIndexRouteImport } from './routes/studio/writing/index'
import { Route as StudioCollectionIndexRouteImport } from './routes/studio/$collection/index'
import { Route as StudioWritingSlugRouteImport } from './routes/studio/writing/$slug'
import { Route as StudioCollectionItemIndexRouteImport } from './routes/studio/$collection/$itemIndex'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWritingIndexRoute = StudioWritingIndexRouteImport.update({
  id: '/studio/writing/',
  path: '/studio/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCollectionIndexRoute = StudioCollectionIndexRouteImport.update({
  id: '/studio/$collection/',
  path: '/studio/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWritingSlugRoute = StudioWritingSlugRouteImport.update({
  id: '/studio/writing/$slug',
  path: '/studio/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCollectionItemIndexRoute =
  StudioCollectionItemIndexRouteImport.update({
    id: '/studio/$collection/$itemIndex',
    path: '/studio/$collection/$itemIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/certifications': typeof CertificationsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/now': typeof NowRoute
  '/open-source': typeof OpenSourceRoute
  '/reading': typeof ReadingRoute
  '/resume': typeof ResumeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/speaking': typeof SpeakingRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/studio/$collection/$itemIndex': typeof StudioCollectionItemIndexRoute
  '/studio/writing/$slug': typeof StudioWritingSlugRoute
  '/studio/$collection/': typeof StudioCollectionIndexRoute
  '/studio/writing/': typeof StudioWritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/certifications': typeof CertificationsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/now': typeof NowRoute
  '/open-source': typeof OpenSourceRoute
  '/reading': typeof ReadingRoute
  '/resume': typeof ResumeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/speaking': typeof SpeakingRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/writing': typeof WritingIndexRoute
  '/studio/$collection/$itemIndex': typeof StudioCollectionItemIndexRoute
  '/studio/writing/$slug': typeof StudioWritingSlugRoute
  '/studio/$collection': typeof StudioCollectionIndexRoute
  '/studio/writing': typeof StudioWritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/certifications': typeof CertificationsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/now': typeof NowRoute
  '/open-source': typeof OpenSourceRoute
  '/reading': typeof ReadingRoute
  '/resume': typeof ResumeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/speaking': typeof SpeakingRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/studio/$collection/$itemIndex': typeof StudioCollectionItemIndexRoute
  '/studio/writing/$slug': typeof StudioWritingSlugRoute
  '/studio/$collection/': typeof StudioCollectionIndexRoute
  '/studio/writing/': typeof StudioWritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/certifications'
    | '/changelog'
    | '/dashboard'
    | '/education'
    | '/experience'
    | '/now'
    | '/open-source'
    | '/reading'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/skills'
    | '/speaking'
    | '/timeline'
    | '/uses'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects/'
    | '/studio/'
    | '/writing/'
    | '/studio/$collection/$itemIndex'
    | '/studio/writing/$slug'
    | '/studio/$collection/'
    | '/studio/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/certifications'
    | '/changelog'
    | '/dashboard'
    | '/education'
    | '/experience'
    | '/now'
    | '/open-source'
    | '/reading'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/skills'
    | '/speaking'
    | '/timeline'
    | '/uses'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects'
    | '/studio'
    | '/writing'
    | '/studio/$collection/$itemIndex'
    | '/studio/writing/$slug'
    | '/studio/$collection'
    | '/studio/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/certifications'
    | '/changelog'
    | '/dashboard'
    | '/education'
    | '/experience'
    | '/now'
    | '/open-source'
    | '/reading'
    | '/resume'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/skills'
    | '/speaking'
    | '/timeline'
    | '/uses'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/projects/'
    | '/studio/'
    | '/writing/'
    | '/studio/$collection/$itemIndex'
    | '/studio/writing/$slug'
    | '/studio/$collection/'
    | '/studio/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  CertificationsRoute: typeof CertificationsRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  NowRoute: typeof NowRoute
  OpenSourceRoute: typeof OpenSourceRoute
  ReadingRoute: typeof ReadingRoute
  ResumeRoute: typeof ResumeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  SpeakingRoute: typeof SpeakingRoute
  TimelineRoute: typeof TimelineRoute
  UsesRoute: typeof UsesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  StudioCollectionItemIndexRoute: typeof StudioCollectionItemIndexRoute
  StudioWritingSlugRoute: typeof StudioWritingSlugRoute
  StudioCollectionIndexRoute: typeof StudioCollectionIndexRoute
  StudioWritingIndexRoute: typeof StudioWritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/writing/': {
      id: '/studio/writing/'
      path: '/studio/writing'
      fullPath: '/studio/writing/'
      preLoaderRoute: typeof StudioWritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$collection/': {
      id: '/studio/$collection/'
      path: '/studio/$collection'
      fullPath: '/studio/$collection/'
      preLoaderRoute: typeof StudioCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/writing/$slug': {
      id: '/studio/writing/$slug'
      path: '/studio/writing/$slug'
      fullPath: '/studio/writing/$slug'
      preLoaderRoute: typeof StudioWritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$collection/$itemIndex': {
      id: '/studio/$collection/$itemIndex'
      path: '/studio/$collection/$itemIndex'
      fullPath: '/studio/$collection/$itemIndex'
      preLoaderRoute: typeof StudioCollectionItemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  CertificationsRoute: CertificationsRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  NowRoute: NowRoute,
  OpenSourceRoute: OpenSourceRoute,
  ReadingRoute: ReadingRoute,
  ResumeRoute: ResumeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  SpeakingRoute: SpeakingRoute,
  TimelineRoute: TimelineRoute,
  UsesRoute: UsesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  StudioCollectionItemIndexRoute: StudioCollectionItemIndexRoute,
  StudioWritingSlugRoute: StudioWritingSlugRoute,
  StudioCollectionIndexRoute: StudioCollectionIndexRoute,
  StudioWritingIndexRoute: StudioWritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
